#!/usr/bin/env bash

#   Copyright The containerd Authors.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#
# Builds and installs cni plugins to /opt/cni/bin,
# and create basic cni config in /etc/cni/net.d.
#
set -euo pipefail

DEFAULT_CNI_PLUGIN_COMMIT=v1.1.1
CNI_DIR=/opt/cni

TMPROOT=$(mktemp -d)

install_cni_plugin() {
  local git_repo git_commit tmp_dir

  git_repo="https://github.com/containernetworking/plugins.git"
  git_commit=${1:-$DEFAULT_CNI_PLUGIN_COMMIT}

  tmp_dir=$(mktemp -d '/tmp/cni-plugins.XXXXX')

  # clone and build
  git clone "${git_repo}" "${tmp_dir}/plugins"
  cd "${tmp_dir}/plugins"
  git checkout "${git_commit}"
  ./build_linux.sh

  # install binary
  mkdir -p "${CNI_DIR}"
  cp -r ./bin "${CNI_DIR}"

  rm -rf "${tmp_dir}"
}

install_cni_plugin $@
